server:
  host: "localhost"
  port: 3000

oauth:
  client_id: "unite-client"
  client_secret: "totally-secret"
  auth_url: "http://localhost:8080/realms/unite/protocol/openid-connect/auth"
  token_url: "http://localhost:8080/realms/unite/protocol/openid-connect/token"

scheduler:
  period: 15